name: "Check PR Title"
description: "Check that the PR title has a ticket reference in it"
runs:
  using: "composite"
  steps:
    - name: "Check PR Title"
      shell: bash
      run: |
        set -e

        PR_NUMBER=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
        PR_TITLE=$(gh pr view "$PR_NUMBER" --json title | jq -r '.title')
        PR_LABELS=$(gh pr view "$PR_NUMBER" --json labels | jq -r '.labels[].name')
        echo "Title: $PR_TITLE Labels: $PR_LABELS"

        if echo "$PR_LABELS" | grep -q "dependencies"; then
          echo "PR has dependencies label, skipping title check"
          exit 0
        fi

        if echo "$PR_TITLE" | grep -qiE 'ENG-[0-9]+'; then
          echo "Title contains a ENG ticket reference"
          exit 0
        else
          echo "Title doesn't include a ENG JIRA ticket ref (expected e.g. ENG-1234)"
          echo "PR title: $PR_TITLE"
          exit 1
        fi
