name: Dependabot Policy Check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:   # lets you trigger it manually from the GitHub UI

jobs:
  dependabot-policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          api-endpoint: ${{ secrets.DEPENDABOT_ENFORCER_API_ENDPOINT }}
          secret: ${{ secrets.DEPENDABOT_ENFORCER_SECRET }}
